// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  define(["jqui", "firebase"], function($jqui, Firebase) {
    var app;
    app = function() {
      var init;
      return init = (function(_this) {
        return function() {
          return _this.firebase = new Firebase('https://conworld.firebaseio.com/forums');
        };
      })(this);
    };
    return app;
  });

}).call(this);
